package pkgclass.skeleton.generator;


import java.awt.Window;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;

public class VariableWindow extends javax.swing.JFrame
{

    /**
     * Creates new form VariableWindow
     */
    public VariableWindow()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTextField1 = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        VarNameLabel = new javax.swing.JLabel();
        VarNameText = new javax.swing.JTextField();
        TypeLabel = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox();
        ArrayCheck = new javax.swing.JCheckBox();
        ArrayListCheck = new javax.swing.JCheckBox();
        GetterCheck = new javax.swing.JCheckBox();
        SetterCheck = new javax.swing.JCheckBox();
        RetrievableCheck = new javax.swing.JCheckBox();
        typeTextBox = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                AddButtonActionPerformed(evt);
            }
        });

        VarNameLabel.setText("Variable Name");

        VarNameText.setText("MyVar");

        TypeLabel.setText("Variable Type");

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "String", "int", "double", "float", "boolean", "Integer", "Boolean", "Custom", "" }));
        typeComboBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                typeComboBoxActionPerformed(evt);
            }
        });

        ArrayCheck.setText("Array");
        ArrayCheck.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ArrayCheckActionPerformed(evt);
            }
        });

        ArrayListCheck.setText("ArrayList");
        ArrayListCheck.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ArrayListCheckActionPerformed(evt);
            }
        });

        GetterCheck.setText("Getter");

        SetterCheck.setText("Setter");

        RetrievableCheck.setText("Retrievable");

        typeTextBox.setText("Variable Type");
        typeTextBox.setEnabled(false);
        typeTextBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                typeTextBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TypeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(typeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(VarNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VarNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GetterCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SetterCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RetrievableCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(typeTextBox))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ArrayCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ArrayListCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VarNameLabel)
                    .addComponent(VarNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TypeLabel)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(typeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ArrayCheck)
                    .addComponent(ArrayListCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GetterCheck)
                    .addComponent(SetterCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RetrievableCheck)
                    .addComponent(AddButton))
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ArrayCheckActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ArrayCheckActionPerformed
    {//GEN-HEADEREND:event_ArrayCheckActionPerformed
        ArrayListCheck.setSelected(false);
    }//GEN-LAST:event_ArrayCheckActionPerformed

    private void ArrayListCheckActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ArrayListCheckActionPerformed
    {//GEN-HEADEREND:event_ArrayListCheckActionPerformed
        ArrayCheck.setSelected(false);
    }//GEN-LAST:event_ArrayListCheckActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_AddButtonActionPerformed
    {//GEN-HEADEREND:event_AddButtonActionPerformed
        String type = "";
        if(typeComboBox.getSelectedItem().toString()== "Custom")
        {
            type = typeTextBox.getText();
        }
        else
        {
            type = typeComboBox.getSelectedItem().toString();
        }
        GUIMain._instance.AddVar(type, VarNameText.getText(), ArrayCheck.isSelected(), ArrayListCheck.isSelected(), GetterCheck.isSelected(), SetterCheck.isSelected(), RetrievableCheck.isSelected());
        
        this.dispose();
    }//GEN-LAST:event_AddButtonActionPerformed

    private void typeComboBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_typeComboBoxActionPerformed
    {//GEN-HEADEREND:event_typeComboBoxActionPerformed
        if(typeComboBox.getSelectedItem() == "Custom")
        {
            typeTextBox.setEnabled(true);
        }
        else
        {
            typeTextBox.setEnabled(false);
        }
    }//GEN-LAST:event_typeComboBoxActionPerformed

    private void typeTextBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_typeTextBoxActionPerformed
    {//GEN-HEADEREND:event_typeTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeTextBoxActionPerformed

    public void preSet(String VarName, String Type, boolean Array, boolean ArrayList, boolean get, boolean set, boolean retrieveable)
    {
        VarNameText.setText(VarName);
        typeComboBox.setSelectedItem(Type);
        ArrayCheck.setSelected(Array);
        ArrayListCheck.setSelected(ArrayList);
        GetterCheck.setSelected(get);
        SetterCheck.setSelected(set);
        RetrievableCheck.setSelected(retrieveable);
    }
    public void preSet(String VarName, String Type, String Custom, boolean Array, boolean ArrayList, boolean get, boolean set, boolean retrieveable)
    {
        VarNameText.setText(VarName);
        typeComboBox.setSelectedItem("Custom");
        typeTextBox.setText(Custom);
        ArrayCheck.setSelected(Array);
        ArrayListCheck.setSelected(ArrayList);
        GetterCheck.setSelected(get);
        SetterCheck.setSelected(set);
        RetrievableCheck.setSelected(retrieveable);
    }
        
    
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VariableWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VariableWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VariableWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VariableWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VariableWindow().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JCheckBox ArrayCheck;
    private javax.swing.JCheckBox ArrayListCheck;
    private javax.swing.JCheckBox GetterCheck;
    private javax.swing.JCheckBox RetrievableCheck;
    private javax.swing.JCheckBox SetterCheck;
    private javax.swing.JLabel TypeLabel;
    private javax.swing.JLabel VarNameLabel;
    private javax.swing.JTextField VarNameText;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox typeComboBox;
    private javax.swing.JTextField typeTextBox;
    // End of variables declaration//GEN-END:variables
}
